apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "eks-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from: []  
