apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eks-app.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "test.lokesh.cloud"
    {{- $configMap := lookup "v1" "ConfigMap" "app" "ssl-prod-eks" -}}
    {{- if $configMap }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ $configMap.data.acm_certificate_arn }}"
    {{- else }}
    {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/teraws-load-balancer-ssl-ports: "443"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "eks-app.selectorLabels" . | nindent 4 }}
